spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1

swagger:
  client:
    - panda-user-service
    - panda-gen-service
    - panda-finace-service
# 关闭默认路由
zuul:
  ignoredServices: '*'
